In [3]:
import numpy as np

In [5]:
list1 = [1,2,3,4,5]

In [6]:
arr = np.array(list1)

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
list2 = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
arr2 = np.array(list2)

In [10]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr2.shape

(3, 3)

In [13]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [20]:
np.random.rand(5,10,3,2).shape

(5, 10, 3, 2)

In [24]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [ ]:
np.